// GENERATED by scripts/gen-icons.mjs from @phosphor-icons/core (MIT). Do not edit;
// change the list in the script and run `npm run icons`.

// The one icon set: Phosphor, Light weight. Every icon in the app comes through
// this file — one weight and one default size across the product is most of
// what makes icons read as a system (invariant 68). Emoji are not icons and are
// not used anywhere (invariant 67, noEmoji.test.ts).
//
// Only re-exports: with `sideEffects` declared in package.json, each page links
// straight to the icon files it uses. Never turn an icon into a top-level call
// like `make(data)` — that kept every icon on every page.

export { Svg, type IconData, type IconProps } from "./icons/Svg";
export { Account } from "./icons/Account";
export { Alert } from "./icons/Alert";
export { ArrowDown } from "./icons/ArrowDown";
export { ArrowLeft } from "./icons/ArrowLeft";
export { ArrowRight } from "./icons/ArrowRight";
export { ArrowUpRight } from "./icons/ArrowUpRight";
export { Basket } from "./icons/Basket";
export { Board } from "./icons/Board";
export { Bolt } from "./icons/Bolt";
export { BrowserIcon } from "./icons/BrowserIcon";
export { Camera } from "./icons/Camera";
export { CaretDown } from "./icons/CaretDown";
export { CaretRight } from "./icons/CaretRight";
export { CaretUp } from "./icons/CaretUp";
export { Check } from "./icons/Check";
export { CheckCircle } from "./icons/CheckCircle";
export { Close } from "./icons/Close";
export { Download } from "./icons/Download";
export { Eye } from "./icons/Eye";
export { Globe } from "./icons/Globe";
export { Hanger } from "./icons/Hanger";
export { Heart } from "./icons/Heart";
export { IdCard } from "./icons/IdCard";
export { Info } from "./icons/Info";
export { LinkIcon } from "./icons/LinkIcon";
export { Lock } from "./icons/Lock";
export { Mail } from "./icons/Mail";
export { Menu } from "./icons/Menu";
export { Note } from "./icons/Note";
export { PaletteIcon } from "./icons/PaletteIcon";
export { Pencil } from "./icons/Pencil";
export { People } from "./icons/People";
export { Photo } from "./icons/Photo";
export { Pin } from "./icons/Pin";
export { Plus } from "./icons/Plus";
export { Question } from "./icons/Question";
export { Refresh } from "./icons/Refresh";
export { Reorder } from "./icons/Reorder";
export { Robot } from "./icons/Robot";
export { Ruler } from "./icons/Ruler";
export { Scales } from "./icons/Scales";
export { Seal } from "./icons/Seal";
export { Search } from "./icons/Search";
export { Shield } from "./icons/Shield";
export { Sparkle } from "./icons/Sparkle";
export { Stack } from "./icons/Stack";
export { Star } from "./icons/Star";
export { Store } from "./icons/Store";
export { Trash } from "./icons/Trash";
export { Upload } from "./icons/Upload";
export { UserIcon } from "./icons/UserIcon";
export { Warning } from "./icons/Warning";
