// GENERATED by scripts/gen-icons.mjs from @phosphor-icons/core (MIT). Do not edit;
// change the list in the script and run `npm run icons`.
// Phosphor "arrow-down".

import { Svg, type IconProps } from "./Svg";

const LIGHT = ["M204.24,148.24l-72,72a6,6,0,0,1-8.48,0l-72-72a6,6,0,0,1,8.48-8.48L122,201.51V40a6,6,0,0,1,12,0V201.51l61.76-61.75a6,6,0,0,1,8.48,8.48Z"];

export function ArrowDown(p: IconProps) {
  return <Svg data={LIGHT} {...p} />;
}
