// GENERATED by scripts/gen-icons.mjs from @phosphor-icons/core (MIT). Do not edit;
// change the list in the script and run `npm run icons`.
// Phosphor "arrow-left".

import { Svg, type IconProps } from "./Svg";

const LIGHT = ["M222,128a6,6,0,0,1-6,6H54.49l61.75,61.76a6,6,0,1,1-8.48,8.48l-72-72a6,6,0,0,1,0-8.48l72-72a6,6,0,0,1,8.48,8.48L54.49,122H216A6,6,0,0,1,222,128Z"];

export function ArrowLeft(p: IconProps) {
  return <Svg data={LIGHT} {...p} />;
}
