// GENERATED by scripts/gen-icons.mjs from @phosphor-icons/core (MIT). Do not edit;
// change the list in the script and run `npm run icons`.
// Phosphor "arrow-right".

import { Svg, type IconProps } from "./Svg";

const LIGHT = ["M220.24,132.24l-72,72a6,6,0,0,1-8.48-8.48L201.51,134H40a6,6,0,0,1,0-12H201.51L139.76,60.24a6,6,0,0,1,8.48-8.48l72,72A6,6,0,0,1,220.24,132.24Z"];

export function ArrowRight(p: IconProps) {
  return <Svg data={LIGHT} {...p} />;
}
