// GENERATED by scripts/gen-icons.mjs from @phosphor-icons/core (MIT). Do not edit;
// change the list in the script and run `npm run icons`.
// Phosphor "arrow-up-right".

import { Svg, type IconProps } from "./Svg";

const LIGHT = ["M198,64V168a6,6,0,0,1-12,0V78.48L68.24,196.24a6,6,0,0,1-8.48-8.48L177.52,70H88a6,6,0,0,1,0-12H192A6,6,0,0,1,198,64Z"];

export function ArrowUpRight(p: IconProps) {
  return <Svg data={LIGHT} {...p} />;
}
