// GENERATED by scripts/gen-icons.mjs from @phosphor-icons/core (MIT). Do not edit;
// change the list in the script and run `npm run icons`.
// Phosphor "browser".

import { Svg, type IconProps } from "./Svg";

const LIGHT = ["M216,42H40A14,14,0,0,0,26,56V200a14,14,0,0,0,14,14H216a14,14,0,0,0,14-14V56A14,14,0,0,0,216,42ZM40,54H216a2,2,0,0,1,2,2V90H38V56A2,2,0,0,1,40,54ZM216,202H40a2,2,0,0,1-2-2V102H218v98A2,2,0,0,1,216,202Z"];

export function BrowserIcon(p: IconProps) {
  return <Svg data={LIGHT} {...p} />;
}
