// GENERATED by scripts/gen-icons.mjs from @phosphor-icons/core (MIT). Do not edit;
// change the list in the script and run `npm run icons`.
// Phosphor "caret-up".

import { Svg, type IconProps } from "./Svg";

const LIGHT = ["M212.24,164.24a6,6,0,0,1-8.48,0L128,88.49,52.24,164.24a6,6,0,0,1-8.48-8.48l80-80a6,6,0,0,1,8.48,0l80,80A6,6,0,0,1,212.24,164.24Z"];

export function CaretUp(p: IconProps) {
  return <Svg data={LIGHT} {...p} />;
}
