// GENERATED by scripts/gen-icons.mjs from @phosphor-icons/core (MIT). Do not edit;
// change the list in the script and run `npm run icons`.
// Phosphor "caret-right".

import { Svg, type IconProps } from "./Svg";

const LIGHT = ["M180.24,132.24l-80,80a6,6,0,0,1-8.48-8.48L167.51,128,91.76,52.24a6,6,0,0,1,8.48-8.48l80,80A6,6,0,0,1,180.24,132.24Z"];

export function CaretRight(p: IconProps) {
  return <Svg data={LIGHT} {...p} />;
}
