// GENERATED by scripts/gen-icons.mjs from @phosphor-icons/core (MIT). Do not edit;
// change the list in the script and run `npm run icons`.
// Phosphor "caret-down".

import { Svg, type IconProps } from "./Svg";

const LIGHT = ["M212.24,100.24l-80,80a6,6,0,0,1-8.48,0l-80-80a6,6,0,0,1,8.48-8.48L128,167.51l75.76-75.75a6,6,0,0,1,8.48,8.48Z"];

export function CaretDown(p: IconProps) {
  return <Svg data={LIGHT} {...p} />;
}
