// GENERATED by scripts/gen-icons.mjs from @phosphor-icons/core (MIT). Do not edit;
// change the list in the script and run `npm run icons`.
// Phosphor "check".

import { Svg, type IconProps } from "./Svg";

const LIGHT = ["M228.24,76.24l-128,128a6,6,0,0,1-8.48,0l-56-56a6,6,0,0,1,8.48-8.48L96,191.51,219.76,67.76a6,6,0,0,1,8.48,8.48Z"];

export function Check(p: IconProps) {
  return <Svg data={LIGHT} {...p} />;
}
