// GENERATED by scripts/gen-icons.mjs from @phosphor-icons/core (MIT). Do not edit;
// change the list in the script and run `npm run icons`.
// Phosphor "x".

import { Svg, type IconProps } from "./Svg";

const LIGHT = ["M204.24,195.76a6,6,0,1,1-8.48,8.48L128,136.49,60.24,204.24a6,6,0,0,1-8.48-8.48L119.51,128,51.76,60.24a6,6,0,0,1,8.48-8.48L128,119.51l67.76-67.75a6,6,0,0,1,8.48,8.48L136.49,128Z"];

export function Close(p: IconProps) {
  return <Svg data={LIGHT} {...p} />;
}
