// GENERATED by scripts/gen-icons.mjs from @phosphor-icons/core (MIT). Do not edit;
// change the list in the script and run `npm run icons`.
// Phosphor "plus".

import { Svg, type IconProps } from "./Svg";

const LIGHT = ["M222,128a6,6,0,0,1-6,6H134v82a6,6,0,0,1-12,0V134H40a6,6,0,0,1,0-12h82V40a6,6,0,0,1,12,0v82h82A6,6,0,0,1,222,128Z"];

export function Plus(p: IconProps) {
  return <Svg data={LIGHT} {...p} />;
}
