// GENERATED by scripts/gen-icons.mjs from @phosphor-icons/core (MIT). Do not edit;
// change the list in the script and run `npm run icons`.
// Phosphor "magnifying-glass".

import { Svg, type IconProps } from "./Svg";

const LIGHT = ["M228.24,219.76l-51.38-51.38a86.15,86.15,0,1,0-8.48,8.48l51.38,51.38a6,6,0,0,0,8.48-8.48ZM38,112a74,74,0,1,1,74,74A74.09,74.09,0,0,1,38,112Z"];

export function Search(p: IconProps) {
  return <Svg data={LIGHT} {...p} />;
}
