// Search words for every garment type, either language — Session 98. Kept apart
// from garmentTaxonomy.ts so a page ships them only when someone searches
// (components/CategoryPicker loads garmentSearch on first use). What belongs here,
// and the test that proves nothing is missing: garmentTaxonomy.ts, rules 2 and 3.

export const GARMENT_ALIASES: Record<string, string[]> = {
  tshirt: ["tee", "t shirt", "t恤", "短袖", "短袖t恤", "半袖", "体恤", "crew neck tee", "graphic tee", "印花t恤", "圆领t恤", "henley"],
  "longsleeve-tee": ["long sleeve tee", "long sleeve t-shirt", "长袖", "长袖t", "长袖体恤"],
  "sport-top": ["sports tee", "training top", "jersey", "cycling jersey", "running top", "运动t恤", "运动上衣", "速干衣", "速干t恤", "球衣", "骑行服", "健身服"],
  polo: ["polo shirt", "polo衫", "翻领t恤", "保罗衫", "高尔夫衫"],
  shirt: ["button-down", "button up", "oxford shirt", "dress shirt", "flannel", "overshirt", "衬衣", "长袖衬衫", "短袖衬衫", "法兰绒衬衫", "牛津纺", "格子衬衫", "恤衫", "衬衫"],
  blouse: ["chiffon top", "lace top", "雪纺衫", "雪纺", "蕾丝衫", "蕾丝上衣", "女衬衫", "娃娃衫", "小衫"],
  tank: ["tank top", "vest top", "camisole", "cami", "singlet", "sleeveless top", "背心", "吊带", "吊带背心", "工字背心", "无袖", "无袖上衣", "运动背心"],
  "tube-top": ["bandeau", "strapless top", "抹胸", "裹胸", "抹胸上衣"],
  "base-layer": ["undershirt", "fitted long sleeve", "打底衫", "打底上衣", "内搭", "高领打底"],
  sweatshirt: ["crewneck sweatshirt", "pullover sweatshirt", "卫衣", "圆领卫衣", "套头衫", "套头卫衣", "运动衫", "绒衫"],
  hoodie: ["hooded sweatshirt", "zip hoodie", "连帽卫衣", "连帽衫", "帽衫", "拉链卫衣"],
  bodysuit: ["body", "leotard", "连体上衣", "紧身连体衣", "连体衣上衣", "unitard", "紧身衣"],
  cardigan: ["cardi", "开衫", "针织开衫", "毛衣开衫", "开襟毛衣", "开襟", "开衫外套", "针织外套"],
  top: ["top", "tops", "上衣", "上装", "tunic", "crop top", "halter top", "露脐上衣", "短款上衣", "女士上衣", "男士上衣"],
  sweater: ["jumper", "pullover", "knit", "knitwear", "turtleneck", "cashmere sweater", "毛衣", "针织衫", "针织", "羊毛衫", "羊绒衫", "套头毛衣", "毛衫", "高领毛衣", "线衣", "针织上衣"],
  "sweater-vest": ["knit vest", "slipover", "针织马甲", "毛衣马甲", "毛线马甲", "毛衣背心"],
  "knit-tank": ["knit cami", "sweater tank", "针织背心", "针织吊带", "针织无袖"],
  blazer: ["suit jacket", "sport coat", "sports jacket", "西装外套", "小西装", "西服外套", "休闲西装", "西装"],
  jacket: ["bomber", "bomber jacket", "coach jacket", "varsity jacket", "fleece jacket", "track jacket", "harrington", "夹克", "短外套", "飞行员夹克", "棒球服", "工装夹克", "抓绒", "摇粒绒", "茄克", "bolero", "sport jacket"],
  "denim-jacket": ["jean jacket", "trucker jacket", "牛仔外套", "牛仔夹克", "牛仔衣"],
  "leather-jacket": ["faux leather jacket", "biker jacket", "moto jacket", "皮衣", "皮夹克", "皮外套", "仿皮", "pu皮衣", "机车夹克", "真皮", "motorcycle jacket", "摩托车夹克"],
  trench: ["trench", "mac", "raincoat", "风衣", "长款风衣", "雨衣"],
  coat: ["overcoat", "wool coat", "peacoat", "topcoat", "大衣", "毛呢外套", "毛呢大衣", "呢子大衣", "羊绒大衣", "双面呢", "呢大衣"],
  "down-jacket": ["puffer", "puffer jacket", "down coat", "parka", "quilted down", "羽绒服", "羽绒衣", "羽绒外套", "面包服", "派克服"],
  "padded-jacket": ["quilted jacket", "insulated jacket", "棉服", "棉衣", "棉袄", "加厚外套"],
  "shell-jacket": ["hardshell", "softshell", "rain jacket", "windbreaker", "anorak", "outdoor jacket", "冲锋衣", "防风衣", "户外外套", "软壳", "ski jacket", "snowboard jacket", "滑雪服"],
  fur: ["fur", "faux fur", "shearling", "teddy coat", "皮草", "貂皮", "皮毛一体", "羊羔毛", "仿皮草"],
  cape: ["cape", "poncho", "cloak", "斗篷", "披风"],
  gilet: ["vest", "gilet", "waistcoat", "puffer vest", "马甲", "坎肩", "羽绒马甲", "西装马甲", "背心外套", "fishing vest", "hunting vest", "渔夫马甲", "马夹", "马甲背心"],
  outerwear: ["outerwear", "外套", "外衣", "男士外套", "女士外套"],
  dress: ["frock", "midi dress", "maxi dress", "mini dress", "sundress", "wrap dress", "连衣裙", "连身裙", "长裙", "中长裙", "公主裙", "茶歇裙", "碎花裙", "法式连衣裙", "裙子"],
  "slip-dress": ["cami dress", "slip", "吊带裙", "吊带连衣裙", "背心裙"],
  "knit-dress": ["sweater dress", "jumper dress", "针织连衣裙", "毛衣裙", "针织裙"],
  "shirt-dress": ["shirtdress", "衬衫裙", "衬衫连衣裙"],
  gown: ["gown", "evening dress", "formal dress", "prom dress", "cocktail dress", "wedding dress", "bridesmaid dress", "礼服", "礼服裙", "晚礼服", "小礼服", "婚纱", "伴娘服", "bridal", "bridesmaid", "mother of the bride"],
  qipao: ["cheongsam", "旗袍", "改良旗袍"],
  hanfu: ["hanfu", "chinese traditional dress", "汉服", "中式", "新中式", "襦裙", "中式连衣裙", "国风"],
  kimono: ["kimono", "yukata", "和服", "浴衣"],
  traditional: ["sari", "saree", "lehenga", "dirndl", "hanbok", "韩服", "纱丽", "莎丽服", "民族服装", "民族服饰", "传统服装", "舞台服装", "演出服", "abaya", "kaftan", "caftan", "kurta", "salwar kameez", "dashiki", "baju melayu", "kilt", "阿尔卑斯少女裙"],
  jumpsuit: ["boilersuit", "coverall", "连体裤", "连身裤", "连体衣", "工装连体", "连体服"],
  playsuit: ["romper", "连体短裤", "短款连体裤"],
  overalls: ["dungarees", "pinafore", "背带裤", "背带裙", "吊带裤", "背带短裤"],
  skirt: ["midi skirt", "mini skirt", "maxi skirt", "半身裙", "半裙", "短裙", "长裙", "中长裙", "裙子", "马面裙", "迷你裙", "及膝裙"],
  "a-line-skirt": ["a line skirt", "skater skirt", "a字裙", "a字半身裙", "伞裙", "蓬蓬裙"],
  "pleated-skirt": ["tennis skirt", "百褶裙", "褶裙", "风琴褶", "百褶半身裙"],
  "pencil-skirt": ["bodycon skirt", "包臀裙", "铅笔裙", "一步裙", "职业裙"],
  "denim-skirt": ["jean skirt", "牛仔裙", "牛仔半身裙"],
  skort: ["skort", "culottes", "裙裤", "裤裙"],
  jeans: ["denim", "skinny jeans", "straight jeans", "牛仔裤", "牛仔长裤", "直筒牛仔裤", "丹宁"],
  pants: ["pants", "trousers", "chinos", "wide-leg", "wide leg", "straight leg", "flared", "裤子", "长裤", "休闲裤", "阔腿裤", "卡其裤", "直筒裤", "哈伦裤", "九分裤", "喇叭裤", "女裤", "男裤", "capris", "palazzo pants", "harem pants", "加绒裤", "裤装"],
  "dress-pants": ["suit trousers", "slacks", "tailored trousers", "西裤", "西装裤", "正装裤"],
  joggers: ["sweatpants", "track pants", "trackpants", "卫裤", "运动裤", "运动长裤", "束脚裤"],
  "cargo-pants": ["cargos", "utility pants", "combat trousers", "工装裤", "工装长裤"],
  "ski-pants": ["snow pants", "ski pants", "rain pants", "hiking pants", "滑雪裤", "冲锋裤", "雨裤", "户外裤", "登山裤"],
  leggings: ["yoga pants", "legging", "打底裤", "瑜伽裤", "紧身裤", "鲨鱼裤", "健身裤", "jeggings", "瑜伽服"],
  shorts: ["bermuda", "chino shorts", "hot pants", "短裤", "五分裤", "热裤", "中裤", "休闲短裤", "cargo shorts"],
  "denim-shorts": ["jean shorts", "cut-offs", "牛仔短裤"],
  "sport-shorts": ["running shorts", "gym shorts", "basketball shorts", "运动短裤", "跑步短裤", "篮球裤"],
  suit: ["two-piece suit", "tuxedo", "西服套装", "西装套装", "西服", "燕尾服", "pant suit", "skirt suit", "套装裙", "长裤套装", "无尾晚礼服"],
  tracksuit: ["track suit", "运动套装", "运动服", "activewear", "运动服饰"],
  "co-ord": ["co-ord", "two-piece set", "matching set", "套装", "两件套", "休闲套装", "时尚套装", "outfit set"],
  "tang-suit": ["mao suit", "zhongshan suit", "唐装", "中山装", "中式套装"],
  uniform: ["workwear", "school uniform", "scrubs", "制服", "职业装", "职业套装", "工作服", "校服", "护士服", "厨师服", "military uniform", "军装", "保安服", "chef jacket", "厨师服", "工装"],
  bra: ["bralette", "胸罩", "文胸", "内衣", "无钢圈", "文胸套装"],
  "sports-bra": ["运动内衣", "运动文胸"],
  underwear: ["briefs", "boxers", "boxer briefs", "panties", "knickers", "trunks", "内裤", "平角裤", "三角裤", "四角裤", "boyshorts", "g-string", "thong", "hipster", "男式内裤", "女式内裤"],
  shapewear: ["corset", "waist trainer", "塑身衣", "塑身", "收腹", "束腰", "美体衣", "bustier", "塑身美体", "塑身内衣"],
  thermals: ["thermal underwear", "long johns", "保暖内衣", "秋衣", "秋裤", "秋衣秋裤", "保暖衣", "发热衣"],
  pajamas: ["pajamas", "pyjamas", "loungewear", "sleepwear", "睡衣", "家居服", "睡衣套装", "居家服", "lounge pants", "情侣睡衣"],
  nightdress: ["nightgown", "nightie", "睡裙"],
  robe: ["bathrobe", "dressing gown", "睡袍", "浴袍", "晨袍"],
  tights: ["pantyhose", "stockings", "hosiery", "丝袜", "连裤袜", "打底袜", "长筒袜", "美腿袜"],
  lingerie: ["lingerie", "petticoat", "underskirt", "slip", "garter", "衬裙", "吊袜带", "内衣配件", "情趣内衣", "胸贴", "其他内衣"],
  swimsuit: ["one-piece swimsuit", "bathing suit", "swimwear", "wetsuit", "泳衣", "泳装", "连体泳衣", "游泳衣", "swim suit", "cover up", "swim dress", "swim skirt", "罩衫"],
  bikini: ["two-piece swimsuit", "tankini", "比基尼", "分体泳衣"],
  "swim-trunks": ["swim trunks", "board shorts", "boardshorts", "泳裤", "沙滩裤", "海滩裤"],
  "rash-guard": ["rash guard", "sun protection jacket", "upf", "防晒衣", "防晒服", "皮肤衣", "冲浪服"],
  sneakers: ["trainers", "running shoes", "basketball shoes", "training shoes", "athletic shoes", "运动鞋", "跑鞋", "跑步鞋", "篮球鞋", "训练鞋", "球鞋", "老爹鞋", "足球鞋", "网球鞋", "徒步鞋", "登山鞋", "hiking shoes"],
  "casual-shoes": ["skate shoes", "court shoes", "休闲鞋", "板鞋", "小白鞋", "德训鞋"],
  "canvas-shoes": ["plimsolls", "帆布鞋"],
  "dress-shoes": ["oxfords", "derby", "brogues", "leather shoes", "皮鞋", "正装鞋", "牛津鞋", "德比鞋", "商务鞋"],
  loafers: ["moccasins", "boat shoes", "乐福鞋", "豆豆鞋", "懒人鞋", "船鞋"],
  flats: ["ballet flats", "mary janes", "单鞋", "平底鞋", "芭蕾舞鞋", "玛丽珍鞋", "浅口鞋", "妈妈鞋"],
  heels: ["pumps", "stilettos", "wedges", "platforms", "高跟鞋", "坡跟鞋", "松糕鞋", "鱼嘴鞋", "细跟", "粗跟"],
  boots: ["ankle boots", "chelsea boots", "combat boots", "snow boots", "knee boots", "靴子", "靴", "马丁靴", "切尔西靴", "雪地靴", "短靴", "长靴", "过膝靴", "工装靴", "女靴", "男靴", "工装鞋"],
  sandals: ["clogs", "凉鞋", "罗马鞋", "沙滩鞋", "洞洞鞋"],
  slippers: ["slides", "flip-flops", "flip flops", "mules", "拖鞋", "人字拖", "凉拖", "棉拖", "穆勒鞋"],
  "cloth-shoes": ["chinese cloth shoes", "布鞋", "老北京布鞋", "千层底", "绣花鞋"],
  "rain-boots": ["wellies", "wellingtons", "rain boots", "雨鞋", "雨靴", "水鞋"],
  shoes: ["shoes", "footwear", "鞋", "鞋子", "女鞋", "男鞋", "其他鞋"],
  socks: ["sock", "袜子", "短袜", "船袜", "中筒袜", "长袜", "运动袜", "tabi socks", "分趾袜", "男袜", "女袜", "棉袜"],
  bag: ["handbag", "backpack", "tote", "crossbody", "wallet", "purse", "包", "包包", "手提包", "双肩包", "斜挎包", "钱包", "腰包", "箱包"],
  hat: ["cap", "beanie", "bucket hat", "beret", "帽子", "棒球帽", "毛线帽", "针织帽", "渔夫帽", "鸭舌帽", "贝雷帽", "fedora", "cowboy hat", "flat cap", "trucker hat", "遮阳帽", "sun hat"],
  scarf: ["shawl", "wrap", "stole", "muffler", "neck warmer", "围巾", "披肩", "丝巾", "围脖", "bandana", "头巾", "neck gaiter", "脖套"],
  belt: ["waist belt", "腰带", "皮带", "腰封", "suspenders", "braces", "belt buckle", "背带", "腰带扣", "cummerbund"],
  gloves: ["mittens", "手套", "连指手套"],
  sunglasses: ["glasses", "eyewear", "太阳镜", "墨镜", "眼镜"],
  tie: ["necktie", "bow tie", "领带", "领结", "tie clip", "领带夹", "pocket square", "ascot", "cravat"],
  cufflinks: ["袖扣", "袖钉"],
  "hair-accessory": ["headband", "scrunchie", "hair clip", "发饰", "发夹", "发箍", "头绳", "发圈", "发带", "hair accessories", "hair ties"],
  jewellery: ["jewelry", "watch", "necklace", "earrings", "ring", "bracelet", "brooch", "首饰", "手表", "项链", "耳环", "戒指", "手链", "胸针", "饰品"],
  accessory: ["accessory", "accessories", "配饰", "服饰配件", "口罩", "雨伞", "earmuffs", "耳罩", "耳包", "handkerchief", "手帕", "arm warmers", "袖套", "leg warmers", "腿套", "wristband", "护腕"],
  other: ["other", "其他"],
};
