// Generates src/components/icons.generated.ts from Phosphor's raw SVGs
// (@phosphor-icons/core, MIT — a devDependency; nothing of it ships at runtime).
//
//   npm run icons
//
// Why generate instead of importing @phosphor-icons/react: every React icon
// there carries all six weights, and we draw one (Light, plus Fill for three
// toggles). Measured in Session 76, 17 UI icons cost 13.6 kB gzipped and 11
// garment icons 11.4 kB — on every page. Extracting only the weights we use
// keeps the same geometry at a fraction of the bytes. Same idea as Logo.tsx,
// which is generated from the master SVG (invariant ㉚).
//
// To add an icon: add a line to ICONS below, run `npm run icons`, then export it
// from components/Icon.tsx (or map it in GarmentIcon.tsx). Names are Phosphor's
// kebab-case file names — browse phosphoricons.com.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const ASSETS = path.join(ROOT, "node_modules", "@phosphor-icons", "core", "assets");
const OUT = path.join(ROOT, "src", "components", "icons.generated.ts");

// Phosphor name → weights to extract. Light is the product weight (Icon.tsx);
// Fill only where a control toggles between the two (rating, like, pin).
const ICONS = {
  // UI
  "arrow-down": ["light"],
  "arrow-left": ["light"],
  "arrow-right": ["light"],
  "arrow-up-right": ["light"],
  "arrows-clockwise": ["light"],
  "arrows-down-up": ["light"],
  "basket": ["light"],
  "browser": ["light"],
  "camera": ["light"],
  "caret-down": ["light"],
  "caret-right": ["light"],
  "check": ["light"],
  "check-circle": ["light"],
  "download-simple": ["light"],
  "envelope-simple": ["light"],
  "eye": ["light"],
  "globe": ["light"],
  "heart": ["light", "fill"],
  "identification-card": ["light"],
  "image-square": ["light"],
  "info": ["light"],
  "lightning": ["light"],
  "link-simple": ["light"],
  "list": ["light"],
  "lock-simple": ["light"],
  "magnifying-glass": ["light"],
  "note": ["light"],
  "palette": ["light"],
  "pencil-simple": ["light"],
  "plus": ["light"],
  "push-pin": ["light", "fill"],
  "question": ["light"],
  "robot": ["light"],
  "ruler": ["light"],
  "scales": ["light"],
  "seal-check": ["light"],
  "shield-check": ["light"],
  "sparkle": ["light"],
  "squares-four": ["light"],
  "star": ["light", "fill"],
  "storefront": ["light"],
  "trash": ["light"],
  "upload-simple": ["light"],
  "user": ["light"],
  "user-circle": ["light"],
  "users-three": ["light"],
  "warning": ["light"],
  "warning-circle": ["light"],
  "x": ["light"],
  // Garments (GarmentIcon.tsx draws the ones Phosphor lacks)
  "baseball-cap": ["light"],
  "belt": ["light"],
  "boot": ["light"],
  "coat-hanger": ["light"],
  "dress": ["light"],
  "hoodie": ["light"],
  "pants": ["light"],
  "shirt-folded": ["light"],
  "sneaker": ["light"],
  "sock": ["light"],
  "t-shirt": ["light"],
};

const pascal = (s) => s.split("-").map((w) => w[0].toUpperCase() + w.slice(1)).join("");
/**
 * An SVG file → the `d` of each of its paths. Phosphor's Light and Fill icons
 * are filled outlines drawn with plain <path d> elements only; anything else
 * (a group, a circle, a stroke attribute) fails the run rather than drawing
 * half an icon.
 */
function parse(file) {
  const svg = fs.readFileSync(file, "utf8");
  const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
  const paths = [];
  let consumed = "";
  for (const m of body.matchAll(/<path d="([^"]*)"\s*\/>/g)) {
    consumed += m[0];
    paths.push(m[1]);
  }
  if (consumed.replace(/\s/g, "") !== body.replace(/\s/g, "")) {
    throw new Error(`unexpected markup in ${file}`);
  }
  return paths;
}

const lines = [
  "// GENERATED by scripts/gen-icons.mjs from @phosphor-icons/core (MIT). Do not edit;",
  "// change the list in the script and run `npm run icons`.",
  "",
  "/** The `d` of each path in a 256×256 icon, drawn with fill=currentColor. */",
  "export type IconData = readonly string[];",
  "",
];
for (const [name, weights] of Object.entries(ICONS)) {
  for (const w of weights) {
    const file = path.join(ASSETS, w, w === "regular" ? `${name}.svg` : `${name}-${w}.svg`);
    if (!fs.existsSync(file)) throw new Error(`no such Phosphor icon: ${name} (${w})`);
    lines.push(`export const ${pascal(name)}${pascal(w)}: IconData = ${JSON.stringify(parse(file))};`);
  }
}
fs.writeFileSync(OUT, lines.join("\n") + "\n");
console.log(`wrote ${path.relative(process.cwd(), OUT)}: ${Object.keys(ICONS).length} icons`);
